### ISSUE TITLE
Docker missing and further issues

### ISSUE THREAD

**Issue by NyistMilan** [plandes/calamr#1]
The docker image seems to be missing from dockerhub: https://hub.docker.com/r/plandes/calamr
Futhermore, when I try to build the docker image that is present inside the repository I get the following errors:

`
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 22904e68-0a49-43b6-bedd-1be9589836bb::v40h2ddmmfnwipwhuqd61goqf: "/target/app": not found
`

If I create the /target/app path, the build goes on until this error:

`ERROR: failed to solve: lstat /var/lib/docker/tmp/buildkit-mount1635969437/target/packages: no such file or directory`

This time no folder creation can bypass this issue.

**Comment by plandes** [comment]
Sorry, it was private and I forgot to make it public.  It is public now.

Please reopen the issue if you can't download it and get it to work.
