### ISSUE TITLE
Coreference Issue

### ISSUE THREAD

**Issue by NyistMilan** [plandes/calamr#4]
d/dog nodes are not merged in the visualization of the graph:

![liu-source-graphviz](https://github.com/plandes/calamr/assets/74186961/46711e51-b68c-4936-8ac2-984880858b4a)

This seems to be more than just a visual error. Is there a way to merge these nodes?

**Comment by plandes** [comment]
Why do you ask?  I'll assume your question is context to AMR summarization, and specifically the work of Liu et al. 2015, which is where this example comes from.

No, Calamr does not merge nodes, and does not do it intentionally.  I can't find the citation right now, but its been shown in the literature that we lose information when nodes are merged.  Instead, the intention is to specifically represent coreferences via a special alignment edge (AMR Coreference is handled by [amr_coref](https://github.com/bjascob/amr_coref)).

Once you have the full graph, you could merge these nodes yourself depending on what you want to do with them.

There are two examples that have a coreference.  This example has a coreference from the source to the summary, and the in the graph it generates, the coreference link is dashed in the graphviz rendering:

```bash
calamr aligncorp coref-bipartite -o example -f txt
```

**Comment by NyistMilan** [comment]
In your conference slides there was an example that merged together two dog named nodes and I thought that was an intended feature in your repository. Thank you for clearing this up.

**Comment by plandes** [comment]
Sorry, I can't find that in the conference slides.  Slide 13 has two `d/dog` nodes (one in each sentence), but this is a coreference and "coreference" is labeled above it.

Maybe there was confusion with the original example in Liu et al 2015, where the nodes are merged.  Again, this algorithm specially does not merge nodes so as to not loose information encoded in the original graphs.
