### ISSUE TITLE
Configuration options

### ISSUE THREAD

**Issue by NyistMilan** [plandes/calamr#5]
Are the config parameters for graph edge similarity threshold and spacy model?

**Comment by plandes** [comment]
Sorry, your question seems to be lacking a subject and I don't understand.  Do you mean a hyperparameter? if so, I don't think there is an "edge similarity" threshold.

I think the answer to your question is you can override configuration with the `--override` command line parameter, which has the syntax `<section>.<property>=<value>`.  You can also create a `.conf` file and use `-c` to point to the file where all the configuration is.  By default it looks for `~/.calamrrc`, but you can also set the file with then environment variable `CALAMRRC` with the path to the configuration file.

The command line (and program) use a framework configuration library that is [fully documented](https://plandes.github.io/util/doc/config.html).
